### ISSUE TITLE
charging from PC on denver/osaka has unusual delay at start

### ISSUE THREAD

**Issue by Ninjastorm380** [moto-common/bug_tracker#2]
**Platform:** 
denver/osaka (?)
**Device:** 
denver/osaka
**Android version:** 
13/HentaiOS
**Description**
device fails to start charging for about 1-3 minutes if plugged into a PC using a USB-A to USB-C data cable. will charge eventually if left to sit, however.

**Symptoms**
failure to begin charging on plugin

**How to reproduce**
connect phone using any USB-A to USB-C data cable, observe that charging fails.

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

**Comment by electimon** [comment]
Tracked here, http://1pwn.ixmoe.com/redmine/issues/2
