### ISSUE TITLE
Can't enable lock screen

### ISSUE THREAD

**Issue by ShadowFungi** [moto-common/bug_tracker#3]
**Platform:** unsure
**Device:** Moto G stylus (2020)
**Android version:** 13

**Description**
When attempting to set the screen lock to something other than none, or swipe, the screen lock settings app will crash, however it will not set the screen lock, and will redirect back to the "Choose a screen lock" page.

**Symptoms**
Unable to set screen lock.
Settings app crashes after two attempts for setting screen lock.
Also unable to set fingerprint lock.

**How to reproduce**
Attempt to set screen lock to something other than swipe, or none, twice. 

**Additional context**
[dmesg.txt](https://github.com/moto-common/bug_tracker/files/10917809/dmesg.txt)
[logcat.txt](https://github.com/moto-common/bug_tracker/files/10917810/logcat.txt)
[locksettings.txt](https://github.com/moto-common/bug_tracker/files/10917917/locksettings.txt)

**Comment by electimon** [comment]
Acknowledged

**Comment by electimon** [comment]
Fixed, latest builds will have this working as of 1-2 weeks before this message
